# EngramDB Python 类型存根（IDE 补全用）
from typing import Any

def open(path: str) -> Db: ...

class Hit:
    id: int
    text: str
    score: float
    semantic: float
    lexical: float
    recency: float
    importance: float
    estimated_tokens: int
    tier: str
    sources: list[str]
    def __repr__(self) -> str: ...

class Collection:
    def remember(self, text: str, subject: str | None = None,
                 tags: list[str] = [], importance: float = 0.5,
                 event_time: int | None = None) -> int: ...
    def recall(self, query: str, budget_tokens: int = 512,
               k_max: int = 64, profile: str = "chat",
               half_life_secs: float | None = None,
               include_cold: bool = False,
               expand_summaries: bool = False) -> list[Hit]: ...
    def forget(self, id: int) -> None: ...
    def forget_subject(self, subject: str) -> int: ...
    def hard_delete(self, id: int) -> None: ...
    def stats(self) -> tuple[int, int]: ...
    def detailed_stats(self) -> dict[str, int]: ...
    def consolidate(self, min_cluster: int = 3) -> tuple[int, int, int]: ...
    def checkpoint(self) -> None: ...

class Db:
    def __new__(cls, path: str) -> "Db": ...
    @staticmethod
    def restore_from(src: str, dest: str) -> "Db": ...
    def create_collection(self, name: str) -> Collection: ...
    def collection(self, name: str) -> Collection: ...
    def collection_names(self) -> list[str]: ...
    def checkpoint_all(self) -> None: ...
    def checkpoint_keep_wal(self) -> None: ...
    def backup_to(self, dest: str) -> str: ...
    def export_jsonl(self, path: str) -> int: ...
    def import_jsonl(self, path: str) -> tuple[int, int]: ...
    def verify(self) -> dict[str, Any]: ...
    def compact(self, retention_secs: int) -> tuple[int, int]: ...
